"use client";

import { useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowUpRight, BrainCircuit, CheckCircle2, Clock3, Cpu, FileStack, GitBranch, Sparkles } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { demoAnalysis, loadAnalysis } from "@/lib/analysis";

const confidenceStyle = (score = 0) => score >= 90 ? "text-emerald-400 border-emerald-500/30 bg-emerald-500/10" : score >= 75 ? "text-amber-400 border-amber-500/30 bg-amber-500/10" : "text-rose-400 border-rose-500/30 bg-rose-500/10";

export default function DashboardPage() {
  const [analysis] = useState(() => loadAnalysis());
  const [why, setWhy] = useState<string | null>(null);
  const [loadingWhy, setLoadingWhy] = useState(false);
  const metadata = analysis.Metadata || demoAnalysis.Metadata!;
  const health = analysis.Health || demoAnalysis.Health!;
  const askWhy = async (risk: (typeof analysis.Risks)[number]) => {
    setLoadingWhy(true); setWhy(null);
    try { const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000"}/insights/why`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ insight: risk }) }); const data = await res.json(); setWhy(data.explanation); }
    catch { setWhy(risk.rationale || "This conclusion is based on relationships and labels found across the uploaded engineering assets."); }
    finally { setLoadingWhy(false); }
  };
  const stages = ["Reading Files", "Extracting Text", "Understanding Diagrams", "Finding Relationships", "Reasoning Across Documents", "Generating Documentation", "Completed"];
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6">
    <section className="flex flex-col gap-4 rounded-3xl border border-zinc-800 bg-gradient-to-br from-indigo-500/10 via-zinc-950 to-zinc-950 p-6 lg:flex-row lg:items-center lg:justify-between">
      <div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-indigo-300"><BrainCircuit className="h-4 w-4" /> Gemma Reasoning</div><h1 className="text-2xl font-bold text-white">One system understanding, across {metadata.files_processed?.length || 0} artifacts.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-400">{analysis.Summary}</p></div>
      <Link href="/graph" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-black hover:bg-zinc-200">Explore graph <ArrowUpRight className="h-4 w-4" /></Link>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[[FileStack, "Files processed", String(metadata.files_processed?.length || 0)], [Cpu, "Components", String(analysis.Components.length)], [GitBranch, "Relationships", String(analysis.Relationships.length)], [AlertTriangle, "Risk signals", String(analysis.Risks.length)], [Clock3, "Processing", `${((metadata.processing_time_ms || 0) / 1000).toFixed(1)}s`]].map(([Icon, label, value]) => { const I = Icon as typeof Cpu; return <div key={String(label)} className="rounded-2xl border border-zinc-800 bg-zinc-950/60 p-4"><I className="h-4 w-4 text-indigo-400" /><p className="mt-4 text-xl font-bold text-white">{value as string}</p><p className="text-xs text-zinc-500">{label as string}</p></div>; })}
    </section>
    <section className="rounded-2xl border border-zinc-800 bg-zinc-950/60 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-white">Reasoning timeline</h2><p className="mt-1 text-xs text-zinc-500">Model: {metadata.model || "Gemma 4"} · overall confidence {metadata.confidence || 0}%</p></div><span className="inline-flex items-center gap-1 text-xs text-emerald-400"><CheckCircle2 className="h-4 w-4" /> Complete</span></div><div className="mt-5 grid gap-2 md:grid-cols-7">{stages.map((stage, index) => <div key={stage} className="flex items-center gap-2 text-[11px] text-zinc-300"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-indigo-500/20 text-indigo-300">{index + 1}</span>{stage}</div>)}</div></section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-zinc-800 bg-zinc-950/60 p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-white">Discovered components</h2><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${confidenceStyle(metadata.confidence)}`}>{metadata.confidence}% confidence</span></div><div className="mt-4 space-y-3">{analysis.Components.map((component) => <div key={component.name} className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-white">{component.name}</p><p className="mt-1 text-xs text-zinc-500">{component.type} · {component.technology || "Technology not identified"}</p></div><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold ${confidenceStyle(component.confidence)}`}>{component.confidence || 0}%</span></div><p className="mt-2 text-sm text-zinc-400">{component.description || component.detail}</p></div>)}</div></div>
      <div className="rounded-3xl border border-zinc-800 bg-zinc-950/60 p-6"><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-emerald-400" /><h2 className="text-lg font-bold text-white">Architecture health</h2></div><div className="mt-5 flex items-center gap-5"><div className="flex h-24 w-24 items-center justify-center rounded-full border-8 border-indigo-500/40 text-2xl font-bold text-white">{health.overall}</div><p className="text-sm text-zinc-400">Overall score reflects evidence found across the complete workspace.</p></div><div className="mt-6 space-y-3">{Object.entries(health).filter(([name]) => name !== "overall").map(([name, score]) => <div key={name}><div className="mb-1 flex justify-between text-xs text-zinc-400"><span className="capitalize">{name}</span><span>{score}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{ width: `${score}%` }} /></div></div>)}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-zinc-800 bg-zinc-950/60 p-6"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-400" /><h2 className="text-lg font-bold text-white">Risk analysis</h2></div><div className="mt-4 space-y-3">{analysis.Risks.map(risk => <div key={risk.title} className="rounded-2xl border border-zinc-800 p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-white">{risk.title}</p><span className="text-xs font-bold text-rose-400">{risk.severity}</span></div><p className="mt-2 text-sm text-zinc-400">{risk.description}</p><button onClick={() => askWhy(risk)} className="mt-3 text-xs font-semibold text-indigo-300 hover:text-white">Why? →</button></div>)}</div></div><div className="rounded-3xl border border-zinc-800 bg-zinc-950/60 p-6"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-indigo-400" /><h2 className="text-lg font-bold text-white">Recommendations</h2></div><div className="mt-4 space-y-3">{analysis.Recommendations.map(item => <div key={item.title} className="rounded-2xl border border-zinc-800 p-4"><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-sm text-zinc-400">{item.description}</p></div>)}</div></div></section>
    {why !== null || loadingWhy ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="max-w-lg rounded-2xl border border-indigo-500/30 bg-zinc-950 p-6 shadow-2xl"><h3 className="font-bold text-white">Why Gemma flagged this</h3><p className="mt-3 text-sm leading-6 text-zinc-300">{loadingWhy ? "Reviewing the cross-document evidence…" : why}</p><button onClick={() => setWhy(null)} className="mt-5 rounded-lg border border-zinc-700 px-3 py-2 text-xs text-zinc-300">Close</button></div></div> : null}
  </div></DashboardLayout>;
}
